- name: Push Spark export files from Pi to Mac
  hosts: "{{ target }}"
  gather_facts: no

  pre_tasks:
    - include_vars: /var/lib/semaphore/.secrets.yml

  tasks:
    - name: Push files to Mac
      synchronize:
        src: "{{ pi_export_path }}"
        dest: "{{ mac_dest }}"
        mode: push
        recursive: yes
        delete: no